const KEY='studyflow-v1';
const days=['segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado','domingo'];
const defaultData={activities:[
{id:'a1',titulo:'Lista de Funções',materia:'Matemática',tipo:'tarefa',prazo:'2026-10-06',prioridade:'alta',dificuldade:'média',tempoEstimado:60,status:'pendente',tempoConcluido:0},
{id:'a2',titulo:'Prova de Genética',materia:'Biologia',tipo:'prova',prazo:'2026-10-09',prioridade:'alta',dificuldade:'difícil',tempoEstimado:120,status:'pendente',tempoConcluido:0},
{id:'a3',titulo:'Trabalho sobre República Velha',materia:'História',tipo:'trabalho',prazo:'2026-10-13',prioridade:'média',dificuldade:'média',tempoEstimado:90,status:'pendente',tempoConcluido:0}],availability:{'segunda-feira':60,'terça-feira':120,'quarta-feira':90,'quinta-feira':120,'sexta-feira':60,'sábado':180,'domingo':0},sessions:[]};
let data=load(),current='inicio',filter='todas';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function uid(){return Math.random().toString(36).slice(2,9)}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'})}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function pct(){return data.activities.length?Math.round(data.activities.filter(a=>a.status==='concluída').length/data.activities.length*100):0}
function isLate(a){return a.status!=='concluída'&&new Date(a.prazo+'T23:59:59')<new Date()}
function activityCard(a,actions=true){return `<article class="activity ${a.status==='concluída'?'done':''}"><div><div class="meta"><span>${a.materia}</span><span class="pill">${a.tipo}</span><span class="pill ${a.prioridade}">${a.prioridade}</span></div><h3>${a.titulo}</h3><div class="meta"><span class="${isLate(a)?'overdue':''}">${isLate(a)?'Atrasada · ':''}${fmtDate(a.prazo)}</span><span>${a.tempoEstimado} min</span><span>${a.status}</span></div></div>${actions?`<div><button class="btn secondary" onclick="toggleActivity('${a.id}')">${a.status==='concluída'?'Reabrir':'Concluir'}</button> <button class="btn danger" onclick="removeActivity('${a.id}')">Excluir</button></div>`:''}</article>`}
function stats(){const pending=data.activities.filter(a=>a.status!=='concluída').length,late=data.activities.filter(isLate).length,tests=data.activities.filter(a=>a.tipo==='prova'&&a.status!=='concluída').length;return `<div class="grid stats"><div class="card stat"><small>Pendentes</small><strong>${pending}</strong></div><div class="card stat"><small>Próximas provas</small><strong>${tests}</strong></div><div class="card stat"><small>Atrasadas</small><strong>${late}</strong></div><div class="card stat"><small>Progresso semanal</small><strong>${pct()}%</strong><div class="progressbar"><span style="width:${pct()}%"></span></div></div></div>`}
function hero(title,sub,button=''){return `<div class="hero"><div><div class="eyebrow">StudyFlow</div><h1>${title}</h1><p>${sub}</p></div>${button}</div>`}
function home(){const upcoming=[...data.activities].filter(a=>a.status!=='concluída').sort((a,b)=>a.prazo.localeCompare(b.prazo)).slice(0,4);const today=data.sessions.filter(s=>s.data===isoToday());return hero('Olá, Ana! 👋','Vamos organizar seus estudos?',`<button class="btn primary" onclick="go('atividades');setTimeout(()=>document.querySelector('#titulo')?.focus(),0)">+ Nova atividade</button>`)+stats()+`<div class="grid layout-2"><div class="card"><div class="section-title"><h2>Próximas atividades</h2><button class="btn secondary" onclick="go('atividades')">Ver todas</button></div><div class="activity-list">${upcoming.length?upcoming.map(a=>activityCard(a,false)).join(''):'<div class="empty">Tudo em dia por aqui ✨</div>'}</div></div><div class="card"><div class="section-title"><h2>Hoje</h2><button class="btn secondary" onclick="go('cronograma')">Cronograma</button></div>${today.length?today.map(sessionMini).join(''):'<div class="empty">Gere seu cronograma para ver as sessões de hoje.</div>'}</div></div>`}
function activities(){const fs=['todas','tarefas','provas','trabalhos','pendentes','concluídas'];let list=data.activities.filter(a=>filter==='todas'||(filter==='tarefas'&&a.tipo==='tarefa')||(filter==='provas'&&a.tipo==='prova')||(filter==='trabalhos'&&a.tipo==='trabalho')||(filter==='pendentes'&&a.status!=='concluída')||(filter==='concluídas'&&a.status==='concluída'));return hero('Atividades','Cadastre, acompanhe e conclua tudo o que precisa fazer.')+`<div class="grid layout-2"><div class="card"><div class="filters">${fs.map(f=>`<button class="filter ${filter===f?'active':''}" onclick="setFilter('${f}')">${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div><div class="activity-list">${list.length?list.map(a=>activityCard(a)).join(''):'<div class="empty">Nenhuma atividade neste filtro.</div>'}</div></div><form class="card" id="activityForm"><div class="section-title"><h2>Nova atividade</h2></div><div class="form-grid"><div class="field full"><label for="titulo">Título</label><input id="titulo" required maxlength="80"></div><div class="field"><label for="materia">Matéria</label><input id="materia" required></div><div class="field"><label for="tipo">Tipo</label><select id="tipo" required><option value="tarefa">Tarefa</option><option value="prova">Prova</option><option value="trabalho">Trabalho</option></select></div><div class="field"><label for="prazo">Data/prazo</label><input id="prazo" type="date" required></div><div class="field"><label for="prioridade">Prioridade</label><select id="prioridade"><option>baixa</option><option selected>média</option><option>alta</option></select></div><div class="field"><label for="dificuldade">Dificuldade</label><select id="dificuldade"><option>fácil</option><option selected>média</option><option>difícil</option></select></div><div class="field"><label for="tempo">Tempo estimado (min)</label><input id="tempo" type="number" min="10" max="1200" step="10" required></div></div><div class="form-actions"><button class="btn primary" type="submit">Adicionar atividade</button></div></form></div>`}
function schedule(){const total=Object.values(data.availability).reduce((a,b)=>a+Number(b||0),0);return hero('Meu Cronograma','Informe sua disponibilidade e deixe o StudyFlow distribuir seus estudos.')+`<div class="grid schedule-layout"><div class="card"><div class="section-title"><h2>Disponibilidade semanal</h2><span class="muted">${Math.floor(total/60)}h${total%60?` ${total%60}min`:''}</span></div><div class="availability">${days.map(d=>`<label class="day-input"><span>${d[0].toUpperCase()+d.slice(1)}</span><input type="number" min="0" step="10" value="${data.availability[d]||0}" data-day="${d}" aria-label="Minutos disponíveis em ${d}"></label>`).join('')}</div><div class="form-actions"><button class="btn primary" onclick="generateSchedule()">Gerar meu cronograma</button></div></div><div><div id="scheduleWarning"></div><div class="schedule">${renderSessions()}</div></div></div>`}
function renderSessions(){if(!data.sessions.length)return `<div class="card empty" style="grid-column:1/-1">Seu cronograma ainda está vazio. Informe seus horários e clique em “Gerar meu cronograma”.</div>`;return days.map(d=>{const ss=data.sessions.filter(s=>weekdayName(s.data)===d);return `<div class="day-card card"><h3>${d}</h3>${ss.length?ss.map(s=>sessionMini(s,true)).join(''):'<div class="muted">Descanso</div>'}</div>`}).join('')}
function progress(){const done=data.activities.filter(a=>a.status==='concluída').length,pending=data.activities.length-done,mins=data.sessions.filter(s=>s.status==='concluída').reduce((n,s)=>n+s.duracao,0),sdone=data.sessions.filter(s=>s.status==='concluída').length;const subjects=[...new Set(data.activities.map(a=>a.materia))];return hero('Progresso','Veja sua evolução e mantenha a constância.')+`<div class="grid progress-grid"><div class="card big-progress"><div class="section-title"><h2>Seu progresso esta semana</h2></div><div class="ring" style="--pct:${pct()}%"><strong>${pct()}%</strong></div><p style="text-align:center" class="muted">${pct()>=75?'Ótimo progresso! Você está avançando muito bem.':pct()>=40?'Bom ritmo! Continue seguindo seu planejamento.':'Cada sessão concluída faz diferença. Continue!'}</p></div><div class="card stat"><small>Atividades concluídas</small><strong>${done}</strong><small>${pending} pendentes</small></div><div class="card stat"><small>Tempo estudado</small><strong>${Math.floor(mins/60)}h${mins%60?` ${mins%60}m`:''}</strong><small>${sdone} sessões realizadas</small></div><div class="card"><h2 style="font-size:18px;margin-top:0">Progresso por matéria</h2>${subjects.map(sub=>{const all=data.activities.filter(a=>a.materia===sub),d=all.filter(a=>a.status==='concluída').length,p=all.length?Math.round(d/all.length*100):0;return `<div class="subject-row"><div><span>${sub}</span><b>${p}%</b></div><div class="progressbar"><span style="width:${p}%"></span></div></div>`}).join('')}</div><div class="card stat"><small>Sequência de estudos</small><strong>${studyStreak()} dias</strong><small>Continue construindo seu ritmo.</small></div></div>`}
function render(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===current));const v=document.querySelector('#view');v.innerHTML=current==='inicio'?home():current==='atividades'?activities():current==='cronograma'?schedule():progress();if(current==='atividades')document.querySelector('#activityForm').addEventListener('submit',addActivity);if(current==='cronograma')document.querySelectorAll('[data-day]').forEach(i=>i.addEventListener('change',e=>{data.availability[e.target.dataset.day]=Math.max(0,Number(e.target.value)||0);save();render()}))}
function go(v){current=v;render();document.querySelector('.sidebar').classList.remove('open');document.querySelector('#view').focus()}
function setFilter(f){filter=f;render()}
function addActivity(e){e.preventDefault();const g=id=>document.querySelector('#'+id).value;data.activities.push({id:uid(),titulo:g('titulo').trim(),materia:g('materia').trim(),tipo:g('tipo'),prazo:g('prazo'),prioridade:g('prioridade'),dificuldade:g('dificuldade'),tempoEstimado:Number(g('tempo')),status:'pendente',tempoConcluido:0});save();render();toast('Atividade adicionada ao seu planejamento.')}
function toggleActivity(id){const a=data.activities.find(x=>x.id===id);a.status=a.status==='concluída'?'pendente':'concluída';if(a.status==='concluída')data.sessions=data.sessions.filter(s=>s.atividadeId!==id||s.status==='concluída');save();render();toast(a.status==='concluída'?'Parabéns! Atividade concluída.':'Atividade reaberta.')}
function removeActivity(id){if(!confirm('Excluir esta atividade?'))return;data.activities=data.activities.filter(a=>a.id!==id);data.sessions=data.sessions.filter(s=>s.atividadeId!==id);save();render();toast('Atividade excluída.')}
function score(a){const type=a.tipo==='prova'?30:a.tipo==='trabalho'?12:5,pri={alta:20,média:10,baixa:0}[a.prioridade],dif={difícil:8,média:4,fácil:0}[a.dificuldade],daysLeft=Math.max(0,(new Date(a.prazo+'T12:00:00')-new Date())/86400000);return type+pri+dif+Math.max(0,30-daysLeft)}
function generateSchedule(){document.querySelectorAll('[data-day]').forEach(i=>data.availability[i.dataset.day]=Math.max(0,Number(i.value)||0));const pending=data.activities.filter(a=>a.status!=='concluída').map(a=>({...a,remaining:Math.max(0,a.tempoEstimado-(a.tempoConcluido||0))})).sort((a,b)=>score(b)-score(a)||a.prazo.localeCompare(b.prazo));data.sessions=[];let cursor=nextMonday(new Date());let unscheduled=0;for(const a of pending){let remaining=a.remaining,guard=0;while(remaining>0&&guard<35){const date=new Date(cursor);date.setDate(cursor.getDate()+guard);const dn=weekdayName(toISO(date)),available=Number(data.availability[dn]||0),used=data.sessions.filter(s=>s.data===toISO(date)).reduce((n,s)=>n+s.duracao,0),room=available-used;if(room>0&&toISO(date)<=a.prazo){const dur=Math.min(60,room,remaining);const startMin=16*60+used+Math.floor(used/60)*10;data.sessions.push({id:uid(),atividadeId:a.id,materia:a.materia,data:toISO(date),horario:`${String(Math.floor(startMin/60)).padStart(2,'0')}:${String(startMin%60).padStart(2,'0')}`,duracao:dur,status:'pendente'});remaining-=dur}guard++}if(remaining>0)unscheduled+=remaining}save();render();if(!pending.length)toast('Não há atividades pendentes para planejar.');else if(!Object.values(data.availability).some(Number))toast('Informe sua disponibilidade antes de gerar.');else if(unscheduled>0){const w=document.querySelector('#scheduleWarning');if(w)w.innerHTML='<div class="warning">Seu tempo disponível pode não ser suficiente para concluir todas as atividades antes dos prazos.</div>';toast('Cronograma gerado com alerta de disponibilidade.')}else toast('Cronograma gerado com sucesso!')}
function completeSession(id){const s=data.sessions.find(x=>x.id===id);if(!s||s.status==='concluída')return;s.status='concluída';const a=data.activities.find(x=>x.id===s.atividadeId);if(a){a.tempoConcluido=Math.min(a.tempoEstimado,(a.tempoConcluido||0)+s.duracao);if(a.tempoConcluido>=a.tempoEstimado)a.status='concluída'}save();render();toast('Sessão concluída. Progresso atualizado!')}
function sessionMini(s,button=false){const a=data.activities.find(x=>x.id===s.atividadeId);return `<div class="${button?'session':'today-session'} ${s.status==='concluída'?'done':''}"><b>${s.horario} · ${s.duracao} min</b><div>${s.materia}${a?` — ${a.titulo}`:''}</div>${button&&s.status!=='concluída'?`<div class="session-actions"><button class="btn secondary" onclick="completeSession('${s.id}')">Concluir sessão</button></div>`:''}</div>`}
function weekdayName(iso){const n=new Date(iso+'T12:00:00').getDay();return ['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'][n]}
function toISO(d){return d.toISOString().slice(0,10)} function isoToday(){return toISO(new Date())}
function nextMonday(d){const x=new Date(d);x.setHours(12,0,0,0);const delta=(8-x.getDay())%7||0;x.setDate(x.getDate()+delta);return x}
function studyStreak(){const dates=[...new Set(data.sessions.filter(s=>s.status==='concluída').map(s=>s.data))].sort().reverse();if(!dates.length)return 0;let streak=1;for(let i=1;i<dates.length;i++){if((new Date(dates[i-1])-new Date(dates[i]))/86400000===1)streak++;else break}return streak}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>go(n.dataset.view)));document.querySelector('#menuBtn').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));window.go=go;window.setFilter=setFilter;window.toggleActivity=toggleActivity;window.removeActivity=removeActivity;window.generateSchedule=generateSchedule;window.completeSession=completeSession;render();
